apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: version-router
spec:
  headers:
    customRequestHeaders:
      X-API-Version: "1"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: weather-api-route
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/weather`) && Headers(`x-version`, `2`)
    kind: Rule
    services:
    - name: weather-api-v2
      port: 3000
  - match: PathPrefix(`/weather`)
    kind: Rule
    services:
    - name: weather-api-v1
      port: 3000
