apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-webapp
  template:
    metadata:
      labels:
        app: weather-webapp
    spec:
      containers:
      - name: weather-webapp
        image: localhost:20000/weather-webapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: weather-webapp
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30000
  selector:
    app: weather-webapp
